# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: ./MangoTomorrow 

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Change working directory
        run: cd ./MangoTomorrow
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build App
        run: npm run build


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: echo "${{ secrets.AWS_PEM }}" > deploy_key.pem
        env:
          PEM_KEY: ${{ secrets.AWS_PEM }}

      - name: Deploy to EC2
        run: |
          chmod 600 deploy_key.pem
          ssh -i deploy_key.pem ec2-user@18.144.107.141 \
          "cd /cppLiftingClub/MangoTomorrow/server && \
          git pull origin main && \
          pm2 restart server.js"

